/* tslint:disable */
/* eslint-disable */
/**
 * Emphasoft API
 * Documentation for test assignment.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthToken,
} from '../models/index';
import {
    AuthTokenFromJSON,
    AuthTokenToJSON,
} from '../models/index';

export interface LoginCreateRequest {
    authToken: Omit<AuthToken, 'token'>;
}

/**
 * 
 */
export class LoginApi extends runtime.BaseAPI {

    /**
     */
    async loginCreateRaw(requestParameters: LoginCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthToken>> {
        if (requestParameters['authToken'] == null) {
            throw new runtime.RequiredError(
                'authToken',
                'Required parameter "authToken" was null or undefined when calling loginCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        const response = await this.request({
            path: `/api/v1/login/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthTokenToJSON(requestParameters['authToken']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthTokenFromJSON(jsonValue));
    }

    /**
     */
    async loginCreate(requestParameters: LoginCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthToken> {
        const response = await this.loginCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
